### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [danielpowell4/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by danielrose7** [comment]
Should be fixed now.

I assume you meant adding the `viewport` meta tag in the `app/view/layouts/application.html.erb` file

I was running just a little too fast yesterday 

![](http://media.giphy.com/media/3oEjHTa6ldVdDi9S1O/giphy-tumblr.gif)

**Comment by BillyMassey** [comment]
You got it! Awesome job Dan.
